service: python-redshift-etl

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  dbConn: postgres://nagaraju:nagaraju@redshift-cluster-1.twewerewrwrw.us-east-1.redshift.amazonaws.com:5439/dev

provider:
  name: aws
  runtime: python3.6
  profile: serverless-admin
  region: us-east-1
  timeout: 300
  environment:
    DB_CONN: ${self:custom.dbConn}
  vpc:
    securityGroupIds:
      - sg-031d82eb144ffbfd6
    subnetIds:
      - subnet-19822446
      - subnet-558a2a74

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ec2:*"
      Resource: "*"

functions:
  etlSample:
    handler: handler.main
    runtime: nodejs12.x
    events:
      - schedule: rate(1 hour)
